interface TypeFormResponseData {
  websiteBuilder: string
  key: string | 'N/A'
  value: string
  region: 'apac' | 'emea'
}

interface TypeFormResponse extends TypeFormResponseData {
  __remove: boolean
}

const typeFormResponsesData: TypeFormResponseData[] = [
  {
    websiteBuilder: 'Wordpress',
    key: 'lakelodgedirect',
    value: 'amblesidetownhouse.co.uk',
    region: 'emea',
  },
  {
    websiteBuilder: 'SiteMinder Website Builder',
    key: 'AnaMandaraVillasDirect',
    value: 'anamandara-resort.com',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'AnasaziCliffsLodgingdirect',
    value: 'anasazicliffslodging.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Guest Traction',
    key: 'anchorinnbeachfrontmotel',
    value: 'anchorinn.co.nz',
    region: 'apac',
  },
  {
    websiteBuilder: 'SiteMinder Website Builder',
    key: 'apartamentosflorida30',
    value: 'apartamentos-florida.es',
    region: 'emea',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'apartamentoscolónplayadirect',
    value: 'apartamentoscolonplaya.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'arivoaptsdirect',
    value: 'arivo.de',
    region: 'emea',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'arnos-manor-hotel',
    value: 'arnosmanorhotel.co.uk',
    region: 'emea',
  },
  {
    websiteBuilder: 'Custom-built website',
    key: 'arthotelmudirect',
    value: 'arthotelmunich.com,arthotelmunich.de,cf.arthotelmunich.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'ashfordmotorlodgedirect',
    value: 'ashfordmotorlodge.co.nz',
    region: 'apac',
  },
  {
    websiteBuilder: 'SiteMinder Website Builder',
    key: 'ashleighcourtmotorinn',
    value: 'ashleighcourt.net.au',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'AstorCourtDirect',
    value: 'astorcourthotel.co.uk',
    region: 'emea',
  },
  {
    websiteBuilder: 'SiteMinder Website Builder',
    key: 'atiuvillasdirect',
    value: 'atiuvillas.com,canvas.siteminder.com',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'avlportdicksondirect',
    value: 'avillion.com',
    region: 'apac',
  },
  {
    websiteBuilder: 'Squarespace',
    key: 'AWAROADIRECT',
    value: 'awaroalodge.co.nz',
    region: 'apac',
  },
  {
    websiteBuilder: 'Webflow',
    key: 'balmoraldirect',
    value: 'balmoralhousehotel.co.uk',
    region: 'emea',
  },
  {
    websiteBuilder: 'Custom-built website',
    key: 'BanffInnDirect',
    value: 'banffinn.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Wix',
    key: 'barefootkuata',
    value: 'barefootkuatafiji.com',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wix',
    key: 'barefootmantadirect',
    value: 'barefootmantafiji.com',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'BERNTISMOUNTAINDIRECT',
    value: 'berntis.com.au,deanv96.sg-host.com',
    region: 'apac',
  },
  {
    websiteBuilder: 'SiteMinder Website Builder',
    key: 'bombuabeachhousedirect',
    value: 'bombuabeachhouse.com',
    region: 'apac',
  },
  {
    websiteBuilder: 'Squarespace',
    key: 'boxgrovedirect',
    value: 'boxgrove.com.au',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'trilogysurfersparadisedirect',
    value: 'bryanf304.sg-host.com,trilogygoldcoast.com.au',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'ritterguthauslaer',
    value: 'buchungen.haus-laer.de,buchungen.rittergut-haus-laer.de,haus-laer.de,relaunch.rittergut-haus-laer.de,rittergut-haus-laer.de',
    region: 'emea',
  },
  {
    websiteBuilder: 'Custom-built website',
    key: 'BudapestMuseumDirect',
    value: 'budapestmuseumcentral.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Custom-built website',
    key: 'butterflygroveinn',
    value: 'butterflygroveinn.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'site123',
    key: 'cameratuadirect',
    value: 'cameratua.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Custom-built website',
    key: 'CampigirSaoTorpesDirect',
    value: 'campigir.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Custom-built website',
    key: 'CampimecoDIRECT',
    value: 'campigir.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'DasNeueCapitolDIRECT',
    value: 'capitol-blb.de',
    region: 'emea',
  },
  {
    websiteBuilder: 'Custom-built website',
    key: 'gladstonecapricornapartments',
    value: 'capricornsuites.com.au',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'pelicanpointwaterfrontresortformerlyknownasca',
    value: 'carnarvonretreat.com.au',
    region: 'apac',
  },
  {
    websiteBuilder: 'SiteMinder Website Builder',
    key: 'CasaAvellanasdirect',
    value: 'casaplayaavellanas.com,casa-playaavellanas.mydirectstay.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'SiteMinder Website Builder',
    key: 'HotelCasaTurquesadirect',
    value: 'casaturquesa.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Custom-built website',
    key: 'CharltonsBanffDirect',
    value: 'charltonsbanff.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'CheetahPlainsPrivateGameReserve',
    value: 'cheetahplains.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Wix',
    key: 'chitraresort',
    value: 'chitraresort.com',
    region: 'apac',
  },
  {
    websiteBuilder: 'Squarespace',
    key: 'clearwatermotelapartmentdirect',
    value: 'clearwatermotel.com.au',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'ClementsHotel',
    value: 'clements.co.nz',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'thecliffsatprincevilledirect',
    value: 'cliffsatprinceville.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'GoDaddy',
    key: 'cccoffsharbourdirect',
    value: 'coffsharbourmotorinn.com.au',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'CormarSuitesDirect',
    value: 'cormarsuites.com',
    region: 'apac',
  },
  {
    websiteBuilder: 'Squarespace',
    key: 'CoronetRidgeResort',
    value: 'coronetridge.co.nz',
    region: 'apac',
  },
  {
    websiteBuilder: 'Custom-built website',
    key: 'craigatinhouseandcourtyarddirect',
    value: 'craigatinhouse.co.uk',
    region: 'emea',
  },
  {
    websiteBuilder: 'NO',
    key: 'CrossroadsInnAndSuitesDirect',
    value: 'crossroadsinnsalem.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Wix',
    key: 'dennarqueestate',
    value: 'dennarqueestate.com',
    region: 'apac',
  },
  {
    websiteBuilder: "don't have a website",
    key: 'serenityholidayhouseportlincolnholidayhouses',
    value: "N/A",
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'doublesixdirect',
    value: 'double-six.com',
    region: 'apac',
  },
  {
    websiteBuilder: 'Google',
    key: 'ecofunco',
    value: 'ecofunco.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'elephantsprdirect',
    value: 'elephantsprings.co.za,southofafrica.co.za,soa.travel,southofafrica.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Wix',
    key: 'EMEAEllenKensington',
    value: 'ellenkensington.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'elranchohaiti',
    value: 'elranchohaiti.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Custom-built website',
    key: 'EscNobDirect',
    value: 'escapeatnobbys.com.au',
    region: 'apac',
  },
  {
    websiteBuilder: 'bluehost',
    key: 'fallriverdirect',
    value: 'estesparkcabins.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'bluehost',
    key: 'pinehavendirect',
    value: 'estesparkcabins.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'SiteMinder Website Builder',
    key: 'TheCottagesatFairHavenCoveDirect',
    value: 'fairhavencove.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'FarmhouseRwandadirect',
    value: 'farmhouserwanda.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'finca360direct',
    value: 'finca360cr.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Custom-built website',
    key: 'fincahotelyerbabuena',
    value: 'fincahotelyerbabuena.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'propio',
    key: 'phfndirect',
    value: 'fornnou-arta.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Custom-built website',
    key: 'fourpointsbysheratonyilanjiaoxi',
    value: 'fourpointsbysheraton-jiaoxi.com,app.lihi.io',
    region: 'apac',
  },
  {
    websiteBuilder: 'Webflow',
    key: 'foxhousescone',
    value: 'foxhousescone.com.au,fox-house-scone.webflow.io',
    region: 'apac',
  },
  {
    websiteBuilder: 'Custom-built website',
    key: 'ApartamentosOliviadirect',
    value: 'gaiarooms.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Custom-built website',
    key: 'HotelCoralDirect',
    value: 'gaiarooms.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'gladstonecbdmotel',
    value: 'gladstonecbdmotel.com.au',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'grafitidirect',
    value: 'grafiti.co.za,southofafrica.co.za,soa.travel,southofafrica.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'graftonhousestudiosdirect',
    value: 'graftonstreetapartments.ie',
    region: 'emea',
  },
  {
    websiteBuilder: 'SiteMinder Website Builder',
    key: 'haleohubedbreakfastdirect',
    value: 'haleohu.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'VolcanoHouseDirect',
    value: 'hawaiivolcanohouse.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'homevillaecoboutique',
    value: 'homevillarusha.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Siweb',
    key: 'hospederiabodasdecamachodirect',
    value: 'hospederiabodasdecamacho.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'hoteldanieldirect',
    value: 'hotel-daniel.de',
    region: 'emea',
  },
  {
    websiteBuilder: 'html5',
    key: 'hotelinlaisen',
    value: 'hotel-hil.de',
    region: 'emea',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'hotellenz',
    value: 'hotel-lenz.de',
    region: 'emea',
  },
  {
    websiteBuilder: 'SiteMinder Website Builder',
    key: 'puriximendirect',
    value: 'hotel-puri.com,hotel-puri.com.tw',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'hotel33kampala',
    value: 'hotel33kampala.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Custom-built website',
    key: 'Hotel98KuchingDirect',
    value: 'hotel98.com.my',
    region: 'apac',
  },
  {
    websiteBuilder: 'SiteMinder Website Builder',
    key: 'HotelBeausejourDirect',
    value: 'hotelbeausejourparis.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Hoststar',
    key: 'HotelBergwirtSchonbrunnDirect',
    value: 'hotelbergwirt.at',
    region: 'emea',
  },
  {
    websiteBuilder: 'Custom-built website',
    key: 'hotelboavistadirect',
    value: 'hotelboavista.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'HOTELLERMITA',
    value: 'hotelermita.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'HotelEspritdAzurdirect',
    value: 'hotelespritdazur.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Custom-built website',
    key: 'hotelitaliatanyahotelbetriebsdirect',
    value: 'hotelitalia.de',
    region: 'emea',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'HotelRestauranteLasBovedasdirect',
    value: 'hotellasbovedas.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'HotelPatioCoraodirect',
    value: 'hotelpatiocorao.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'siteminder',
    key: 'hotelpompaelodirect',
    value: 'hotelpompaelo.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Custom-built website',
    key: 'RebstockMeiringen',
    value: 'hotelrebstock.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Custom-built website',
    key: 'hotelriazordirect',
    value: 'hotelriazor.mx',
    region: 'emea',
  },
  {
    websiteBuilder: 'SiteMinder Website Builder',
    key: 'hotelveleirodirect',
    value: 'hotelveleiro.pt',
    region: 'emea',
  },
  {
    websiteBuilder: 'Webflow',
    key: 'HotelZazzdirect',
    value: 'hotelzazz.com,hotel-zazz.webflow.io',
    region: 'emea',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'howbeckhoteldirect',
    value: 'howbeck.co.uk',
    region: 'emea',
  },
  {
    websiteBuilder: 'SiteMinder Website Builder',
    key: 'TheHurdwickDirect',
    value: 'hurdwick.com,thehurdwick.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Siteminder',
    key: 'iconhotelsantiagodirect',
    value: 'iconchile.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Custom-built website',
    key: 'ShanghaiIFCResidence',
    value: 'ifcresidence.com,ifcr.circle-soft.com',
    region: 'apac',
  },
  {
    websiteBuilder: 'Custom-built website',
    key: 'IlDelphinoDIRECT',
    value: 'ildelfino.com.au',
    region: 'apac',
  },
  {
    websiteBuilder: 'Duda',
    key: 'indilaboracay',
    value: 'indilaboracay.com',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'ironhorseinndirect',
    value: 'ironhorseinndeadwood.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'ivybythesea',
    value: 'ivybythesea.co.uk',
    region: 'emea',
  },
  {
    websiteBuilder: 'SiteMinder Website Builder',
    key: 'JogllandHotelPrettenhoferDIRECT',
    value: 'jogllandhotel.at',
    region: 'emea',
  },
  {
    websiteBuilder: 'Duda',
    key: 'JoktelFishRiverResortdirect',
    value: 'joktelfishriverresort.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'GoDaddy',
    key: 'jlsterlakeview',
    value: 'jolsterlakeview.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'KabanHotelandCasinoBoracay',
    value: 'kabanboracay.com',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'baankantiangdirect',
    value: 'kantiang.se',
    region: 'apac',
  },
  {
    websiteBuilder: 'Custom-built website',
    key: 'KappaSensesUbudDirect',
    value: 'kappasenses.com',
    region: 'apac',
  },
  {
    websiteBuilder: 'No Wordpress',
    key: 'KinnGuesthouseDowntownDirect',
    value: 'kinnguesthouse.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'SiteMinder Website Builder',
    key: 'kirketonhtldirect',
    value: 'kirketon.com.au',
    region: 'apac',
  },
  {
    websiteBuilder: 'Squarespace',
    key: 'CASADELRECTORDIRECT',
    value: 'lacasadelrector.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'SiteMinder Website Builder',
    key: 'lacopainnbeachhotel',
    value: 'lacoparesort.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'lalipa2',
    value: 'lalipa.es',
    region: 'emea',
  },
  {
    websiteBuilder: 'Custom-built website',
    key: 'LaMarsellesadirect',
    value: 'lamarsellesa.es',
    region: 'emea',
  },
  {
    websiteBuilder: 'google site',
    key: 'letranslondirect',
    value: 'letranslon.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'SiteMinder Website Builder',
    key: 'limestonemansiondirect',
    value: 'limestonemansion.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'lindhotelgmbhdirect',
    value: 'lind-hotel.de',
    region: 'emea',
  },
  {
    websiteBuilder: 'SiteMinder Website Builder',
    key: 'theroyalhotedirect',
    value: 'liverpool-royalhotel.co.uk',
    region: 'emea',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'livingamcarlsplatz',
    value: 'livingcarlsplatz.de',
    region: 'emea',
  },
  {
    websiteBuilder: 'No',
    key: 'ludingtonpierhousedirect',
    value: 'ludingtonpierhouse.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'paraisoapartamentosdirect',
    value: 'madeiraparaiso.com,madeiraparaiso.pt,sevenscope.dev',
    region: 'emea',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'MADINGLEYDIRECT',
    value: 'madingleyhall.cam.ac.uk,madingleyhall.co.uk',
    region: 'emea',
  },
  {
    websiteBuilder: 'Squarespace',
    key: 'themarquettehotelmadison',
    value: 'madisonmarquettehotel.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Custom-built website',
    key: 'magnumsbackpackersdirect',
    value: 'magnums.com.au',
    region: 'apac',
  },
  {
    websiteBuilder: 'google',
    key: 'mamkaibaebeachresort-kohchang',
    value: 'mamkaibaehotel.com,mamkaibaehotel.com.th',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'marahaubeachcampdirect',
    value: 'marahaubeachcamp.co.nz',
    region: 'apac',
  },
  {
    websiteBuilder: 'Custom-built website',
    key: 'mauritsapartmentssuites',
    value: 'mauritsapartments.nl',
    region: 'emea',
  },
  {
    websiteBuilder: 'Webflow',
    key: 'mcmmotellit',
    value: 'mcmmotel.co.nz',
    region: 'apac',
  },
  {
    websiteBuilder: 'SiteMinder Website Builder',
    key: 'metriahoteldirect',
    value: 'metriahotel.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'SiteMinder Website Builder',
    key: 'MoleCreekCabinsDirect',
    value: 'molecreekcabins.com.au',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'monasterysuitesnldirect',
    value: 'monasteryspa.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Custom-built website',
    key: 'moontabayaccommodation',
    value: 'moontabayaccommodation.com',
    region: 'apac',
  },
  {
    websiteBuilder: 'Custom-built website',
    key: 'mouseshouse',
    value: 'mouseshouse.com.au,mousesretreat.com.au',
    region: 'apac',
  },
  {
    websiteBuilder: 'HTML, CSS y JS',
    key: 'mysuitemadrid',
    value: 'mysuitemadrid.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Silverstripe',
    key: 'pavnthbrndirect',
    value: 'N/A',
    region: 'apac',
  },
  {
    websiteBuilder: 'Custom-built website',
    key: 'NeohostelBerlinDirect',
    value: 'neohostel.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'theoldvine1direct',
    value: 'oldvinewinchester.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Custom-built website',
    key: 'ozoarenaamsterdam',
    value: 'ozo-hotels.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'pacuaremountainlodge',
    value: 'pacuaremountainloadge.com,pacuaremountainlodge.com.en',
    region: 'emea',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'parklandscalliope',
    value: 'parklands-resort.com.au',
    region: 'apac',
  },
  {
    websiteBuilder: 'Squarespace',
    key: 'ParksideHotelandApartmentsdirect',
    value: 'parksidehotel.co.nz',
    region: 'apac',
  },
  {
    websiteBuilder: 'Custom-built website',
    key: 'PebblyBeachEscapeDirect',
    value: 'pebblybeach.com.au',
    region: 'apac',
  },
  {
    websiteBuilder: 'Processwire',
    key: 'PenguinHotelSouthBeachDirect',
    value: 'penguinhotel.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Havealook',
    key: 'pericoeretreatbb',
    value: 'pericoeretreat.com.au',
    region: 'apac',
  },
  {
    websiteBuilder: 'SiteMinder Website Builder',
    key: 'petitmiradordirect',
    value: 'petitmirador.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'SiteMinder Website Builder',
    key: 'AparthotelPordoSoldirect1',
    value: 'pordosol.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Squarespace',
    key: 'PortageResortDirect',
    value: 'portageresort.co.nz',
    region: 'apac',
  },
  {
    websiteBuilder: 'Custom-built website',
    key: 'portocovopraiahotelandspadirect',
    value: 'portocovopraiahotelspa.pt',
    region: 'emea',
  },
  {
    websiteBuilder: 'processwire',
    key: 'presidenthotelmiamibeachdirect',
    value: 'presidentsouthbeach.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'processwire',
    key: 'presidentvillahotelmiamibeachdirect',
    value: 'presidentvillamiami.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Custom-built website',
    key: 'pugsealanatolefrancedirect',
    value: 'pugseal.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Custom-built website',
    key: 'pugsealoaxacadirect',
    value: 'pugseal.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Custom-built website',
    key: 'pugsealpolancodirect',
    value: 'pugseal.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Custom-built website',
    key: 'quentinamsterdamhotel',
    value: 'quentinhotels.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Custom-built website',
    key: 'quentinprague',
    value: 'quentinhotels.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Custom-built website',
    key: 'quentinxlpotsdamerplatz',
    value: 'quentinhotels.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Squarespace',
    key: 'RATANUILODGEDIRECT',
    value: 'ratanuilodge.com',
    region: 'apac',
  },
  {
    websiteBuilder: 'Custom-built website',
    key: 'riadzeitounpalace',
    value: 'riadzeitoun.com,riadzeitoun.ma',
    region: 'emea',
  },
  {
    websiteBuilder: 'Custom-built website',
    key: 'splashinndiveresortdirect',
    value: 'roatansplashinn.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Custom-built website',
    key: 'RoyalCanadianLodgedirect',
    value: 'royalcanadianlodge.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'RSVPMotelDirect',
    value: 'rsvphotel.co',
    region: 'emea',
  },
  {
    websiteBuilder: 'SiteMinder Website Builder',
    key: 'stfranresandmardirect',
    value: 'saintfrancisresort.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'SandpiperonSmithsLakeDirect',
    value: 'sandpiperonsmithslake.com',
    region: 'apac',
  },
  {
    websiteBuilder: 'N/A',
    key: '2496sanremohoteldirect',
    value: 'sanremohotel.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'SiteMinder Website Builder',
    key: 'LunaBlancaDirect',
    value: 'schwangau-homes.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'SenseAsiaResortDirect',
    value: 'sense-asia.com,senseasia20037.live-website.com',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'shangriladirect',
    value: 'shangrila.co.za,shangri-la.co.za,southofafrica.co.za,soa.travel,southofafrica.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'shantararesortdirect',
    value: 'shantara.com.au',
    region: 'apac',
  },
  {
    websiteBuilder: 'DNS.BIZSITESERVICE.COM',
    key: 'siestamoteldirect',
    value: 'siestamotel.net',
    region: 'emea',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'skyzhotelkampala',
    value: 'skyzhotelkampala.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Webflow',
    key: 'HotelSmartLivinDirect',
    value: 'smartlivin.at,smartlivin.webflow.io',
    region: 'emea',
  },
  {
    websiteBuilder: 'SiteMinder Website Builder',
    key: 'snobhollowinndirect',
    value: 'snobhollowinn.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Squarespace',
    key: 'SohoAucklandDIRECT',
    value: 'soholuxuryhotels.com',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'spaceqcapsulehoteldirect',
    value: 'spaceq.com.au',
    region: 'apac',
  },
  {
    websiteBuilder: 'SiteMinder Website Builder',
    key: 'stagewelldirect',
    value: 'stagewellhotel.com',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'StarHotel',
    value: 'starhotel.scot',
    region: 'emea',
  },
  {
    websiteBuilder: 'Custom-built website',
    key: 'scubahavefuvahmulahdiveguesthouse',
    value: 'stayatscubahaven.com ,aquaatoll.com',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'StaysHoteldirect',
    value: 'stays.com.my',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'KINNCapsuleDIRECT',
    value: 'staywithkinn.com',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'KINNHabitatDIRECT',
    value: 'staywithkinn.com',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'KINNStudiosdirect',
    value: 'staywithkinn.com',
    region: 'apac',
  },
  {
    websiteBuilder: 'SiteMinder Website Builder',
    key: 'jesmonddenedirect',
    value: 'stpancrashotelgroup.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'SiteMinder Website Builder',
    key: 'jesmonddenesuitesstpancrasdirect',
    value: 'stpancrashotelgroup.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'SiteMinder Website Builder',
    key: 'princesshoteldirect',
    value: 'stpancrashotelgroup.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Innsight',
    key: 'stpetebeachsuitesdirect',
    value: 'stpetebeachsuites.com,parkshoresuites.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'SiteMinder Website Builder',
    key: 'sunrisedirect',
    value: 'sunrisegiliair.com',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'taipabeachresort',
    value: 'taipabeachresort.co.nz',
    region: 'apac',
  },
  {
    websiteBuilder: 'Squarespace',
    key: 'thatchcayedirect',
    value: 'thatchcayebelize.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Canva',
    key: 'thearcherretreat',
    value: 'thearcher.au',
    region: 'apac',
  },
  {
    websiteBuilder: 'Custom-built website',
    key: 'BearskinLodgeontheRiverdirect',
    value: 'thebearskinlodge.com,bearskinlodge.imegtest.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'No site is live: https://www.thebuenaparkhotel.com/',
    key: 'thebuenaparkhotel&suitesdirect',
    value: 'thebuenaparkhotel.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Wix',
    key: 'CarltonParkHotelDirect',
    value: 'thecarltonparkhotel.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'SiteMinder Website Builder',
    key: 'TheChurchDirect',
    value: 'thechurchgawler.com.au',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'unionlodgepartnersinc',
    value: 'thecolonialcrest.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Webflow',
    key: 'DelatiteHotelDirect',
    value: 'thedelatitehotel.com.au,the-delatite-hotel.webflow.io',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'thefrogmilhoteldirect',
    value: 'thefrogmill.co.uk',
    region: 'emea',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'The GeorgeMaltaDirect',
    value: 'thegeorgemalta.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'SiteMinder Website Builder',
    key: 'TheGeraldApartmentHotelDirect',
    value: 'thegerald.com.au',
    region: 'apac',
  },
  {
    websiteBuilder: 'SiteMinder Website Builder',
    key: 'TheLazyDuckInnDIRECT',
    value: 'thelazyduckinn.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'GoDaddy',
    key: 'thelighthouseinn',
    value: 'thelighthouseinn.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'thelomboklodgedirect',
    value: 'thelomboklodge.com,tllhospitality.com',
    region: 'apac',
  },
  {
    websiteBuilder: 'Custom-built website',
    key: 'themargaretrivertrufflefarm',
    value: 'themargaretrivertrufflefarm.com.au',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'ThePortlandLodgeHoteldirect',
    value: 'theportlandashington.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'GoDaddy',
    key: 'thebewdleyhotel',
    value: 'theseabirdsuites.co.uk',
    region: 'emea',
  },
  {
    websiteBuilder: 'GoDaddy',
    key: 'thespringsrsrtandspaatarnldirect',
    value: 'thespringscostarica.com,thespringscr.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Google Sites',
    key: 'tilosvilladirect',
    value: 'tilosvilla.com,it.tilosvilla.com,fr.tilosvilla.com,gr.tilosvilla.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'SiteMinder Website Builder',
    key: 'tomsquareboutiquehotel',
    value: 'tomsquareboutiquehotel.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Webflow',
    key: 'toudaecolodge',
    value: 'touda.fr,touda.webflow.io',
    region: 'emea',
  },
  {
    websiteBuilder: 'Webflow',
    key: 'umaruralboutique',
    value: 'umaruralboutique.com,umaruralboutique.webflow.io',
    region: 'emea',
  },
  {
    websiteBuilder: 'Wix',
    key: 'upstairsdownstairscolivingbukitbintang',
    value: 'upstairs-downstairs.co',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wix',
    key: 'upstairsdownstairscolivingkampungpandan',
    value: 'upstairs-downstairs.co',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'VillaBorobudurDirect',
    value: 'villaborobudurresort.com',
    region: 'apac',
  },
  {
    websiteBuilder: 'Custom-built website',
    key: 'VillaEiraDirect',
    value: 'villaeira.pt',
    region: 'apac',
  },
  {
    websiteBuilder: 'SiteMinder Website Builder',
    key: 'villanestordirect',
    value: 'villanestor.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'FRAMER',
    key: 'BriccodiNizzaSRL',
    value: 'villavinory.com,villavinory.framer.website',
    region: 'emea',
  },
  {
    websiteBuilder: 'Framer',
    key: 'VillaVinoryLaMandragolaDIRECT',
    value: 'villavinory.framer.website,villavinory.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'FRAMER',
    key: 'VillaVinoryTenutailSognoDIRECT',
    value: 'villavinory.framer.website,villavinory.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Custom-built website',
    key: 'WHITSUNDAYSATSDIRECT',
    value: 'wahi.com.au',
    region: 'apac',
  },
  {
    websiteBuilder: 'Custom-built website',
    key: 'waikikiheritagehotel',
    value: 'waikikiheritagehotel.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'GoDaddy',
    key: 'PeaceLodgeDirect',
    value: 'waterfallgardens.com,peacelodgecr.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Drupal',
    key: 'Watsonsbaydirect',
    value: 'watsonsbayhotel.com.au,watsonsbay.staging.laundy.doghouse.cloud',
    region: 'apac',
  },
  {
    websiteBuilder: 'Webflow',
    key: 'whalerscoveresort',
    value: 'whalerscoveresort.com,whalers-cove.webflow.io',
    region: 'emea',
  },
  {
    websiteBuilder: 'Silver Stripe',
    key: 'WildernessLodgeArthursPassDirect',
    value: 'wildernesslodge.co.nz',
    region: 'apac',
  },
  {
    websiteBuilder: 'Silverstripe',
    key: 'WildernessLodgeLakeMoerakidirect',
    value: 'wildernesslodge.co.nz',
    region: 'apac',
  },
  {
    websiteBuilder: 'Squarespace',
    key: 'worldwidebackpackersdirect',
    value: 'worldwidebackpackers.co.nz',
    region: 'apac',
  },
  {
    websiteBuilder: 'Squarespace',
    key: 'WQHotelDirect',
    value: 'wqhotel.co.nz',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: '81BALESTIERDIRECT',
    value: 'wwhotels.com,local.wwhotels.com,wwhotels.emarketingeye.net',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: '81chinatowndirect',
    value: 'wwhotels.com,local.wwhotels.com,wwhotels.emarketingeye.net',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: '81heritagedirect',
    value: 'wwhotels.com,local.wwhotels.com,wwhotels.emarketingeye.net',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'H81GOLDDIRECT',
    value: 'wwhotels.com,local.wwhotels.com,wwhotels.emarketingeye.net',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'H81SINGAPOREDIRECT',
    value: 'wwhotels.com,local.wwhotels.com,wwhotels.emarketingeye.net',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'hot81elegancedirect',
    value: 'wwhotels.com,local.wwhotels.com,wwhotels.emarketingeye.net',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'hotel81bugisdirect',
    value: 'wwhotels.com,local.wwhotels.com,wwhotels.emarketingeye.net',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'HOTEL81CHANGIDIRECT',
    value: 'wwhotels.com,local.wwhotels.com,wwhotels.emarketingeye.net',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'hotel81classicdirect',
    value: 'wwhotels.com,local.wwhotels.com,wwhotels.emarketingeye.net',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'hotel81cosydirect',
    value: 'wwhotels.com,local.wwhotels.com,wwhotels.emarketingeye.net',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'hotel81dicksondirect',
    value: 'wwhotels.com,local.wwhotels.com,wwhotels.emarketingeye.net',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'hotel81fujidirect',
    value: 'wwhotels.com,local.wwhotels.com,wwhotels.emarketingeye.net',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'hotel81geylangdirect',
    value: 'wwhotels.com,local.wwhotels.com,wwhotels.emarketingeye.net',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'hotel81joydirect',
    value: 'wwhotels.com,local.wwhotels.com,wwhotels.emarketingeye.net',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'hotel81kovandirect',
    value: 'wwhotels.com,local.wwhotels.com,wwhotels.emarketingeye.net',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'hotel81lavenderdirect',
    value: 'wwhotels.com,local.wwhotels.com,wwhotels.emarketingeye.net',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'Hotel81luckydirect',
    value: 'wwhotels.com,local.wwhotels.com,wwhotels.emarketingeye.net',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'hotel81orchiddirect',
    value: 'wwhotels.com,local.wwhotels.com,wwhotels.emarketingeye.net',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'hotel81osakadirect',
    value: 'wwhotels.com,local.wwhotels.com,wwhotels.emarketingeye.net',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'hotel81palacedirect',
    value: 'wwhotels.com,local.wwhotels.com,wwhotels.emarketingeye.net',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'hotel81rochordirect',
    value: 'wwhotels.com,local.wwhotels.com,wwhotels.emarketingeye.net',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'hotel81selegiedirect',
    value: 'wwhotels.com,local.wwhotels.com,wwhotels.emarketingeye.net',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'hotel81stardirect',
    value: 'wwhotels.com,local.wwhotels.com,wwhotels.emarketingeye.net',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'HOTELBOSSDIRECT',
    value: 'wwhotels.com,local.wwhotels.com,wwhotels.emarketingeye.net',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'HotelMiDirect',
    value: 'wwhotels.com,local.wwhotels.com,wwhotels.emarketingeye.net',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'hotelmirochordirect',
    value: 'wwhotels.com,local.wwhotels.com,wwhotels.emarketingeye.net',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'HotelSakurabyVenueDirect',
    value: 'wwhotels.com,local.wwhotels.com,wwhotels.emarketingeye.net',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'htl81princessdirect',
    value: 'wwhotels.com,local.wwhotels.com,wwhotels.emarketingeye.net',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'htl81tristardirect',
    value: 'wwhotels.com,local.wwhotels.com,wwhotels.emarketingeye.net',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'valuebalestierdirect',
    value: 'wwhotels.com,local.wwhotels.com,wwhotels.emarketingeye.net',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'valuehotelnicedirect',
    value: 'wwhotels.com,local.wwhotels.com,wwhotels.emarketingeye.net',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'valuehotelthomdirect',
    value: 'wwhotels.com,local.wwhotels.com,wwhotels.emarketingeye.net',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'vbencoolendirect',
    value: 'wwhotels.com,local.wwhotels.com,wwhotels.emarketingeye.net',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'VenueHoteldirect',
    value: 'wwhotels.com,local.wwhotels.com,wwhotels.emarketingeye.net',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'VENUELILYDIRECT',
    value: 'wwhotels.com,local.wwhotels.com,wwhotels.emarketingeye.net',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'vlavenderdirect',
    value: 'wwhotels.com,local.wwhotels.com,wwhotels.emarketingeye.net',
    region: 'apac',
  },
  {
    websiteBuilder: 'Wordpress',
    key: 'BishopStreetSuitesDirect',
    value: 'bishopsuites.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'SiteMinder Website Builder',
    key: 'themorningtoncamdendirect',
    value: 'morningtoncamden.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'GoDaddy',
    key: 'safirabludirect',
    value: 'safirablu.com',
    region: 'emea',
  },
  {
    websiteBuilder: 'Custom-built website',
    key: 'ywcahotelvancouverdirect',
    value: 'ywcahotel.com,ywcavan.org',
    region: 'emea',
  },
]


const typeFormResponses: TypeFormResponse[] = (() => {
  return typeFormResponsesData.map(response => {
    const notEmbedding = response.value === 'N/A' || response.value.includes('N/A')
    const noWebsite = response.value === '' || response.value.trim() === ''
    const noKey = response.key === '' || response.key.trim() === ''

    return {
      ...response,
      "__remove": notEmbedding || noWebsite || noKey,
    }
  })
})()

export default typeFormResponses
